### ISSUE TITLE
Add class name to {pixeltrix} sprite objects

### ISSUE THREAD

**Issue by trevorld** [matt-dray/pixeltrix#36]
In particular in the not too distant future `{bittermelon}` will be getting the ability to print sprites to the R terminal and it would be nice to be able to more easily write an `as_bm_pixmap()` S3 method for `{pixeltrix}` sprites in order to print/play with them too:

![Screenshot from 2024-05-29 21-52-18](https://github.com/matt-dray/pixeltrix/assets/2433259/4ab01bef-fd5c-47da-b6f1-25ab7a142bbf)

**Comment by matt-dray** [comment]
Thanks for the suggestion. {bittermelon} looks great and I look forward to its expansion.

**Comment by trevorld** [comment]
Awesome, thanks!  Conversion from `{pixeltrix}` to `{bittermelon}` seems to be working now in https://github.com/trevorld/bittermelon/pull/65

```r
library("bittermelon")
library("hexfont")
library("pixeltrix")
font <- hexfont::unifont(ucp = str2ucp("🐉"))
dragon <- as_bm_bitmap("🐉", font = font) |> 
    bm_glow() |>
    bm_extend(sides = 1L)
pt <- as.matrix(dragon, first_row_is_top = TRUE) |> 
    as_pixeltrix()
# class(pt)
# draw_pixels(pt)
pm <- as_bm_pixmap(pt)
print(pm, compress = "v")
```

![image](https://github.com/matt-dray/pixeltrix/assets/2433259/af37717e-54f2-4a07-8267-3e9c7662ef89)
